pipeline:
  # TESTS:
  # We run tests in parallel. Tests run in a copy of the working directory to avoid conflict
  test_legacy:
    group: test
    image: lampepfl/dotty:2017-10-07
    commands:
      - cp -R . /tmp/0/ && cd /tmp/0/
      - ./project/scripts/sbt legacyTests

  test:
    group: test
    image: lampepfl/dotty:2017-10-07
    commands:
      - cp -R . /tmp/1/ && cd /tmp/1/
      - ./project/scripts/sbt testAll
      - ./project/scripts/sbt ";dotty-bench/jmh:run 1 1 tests/run/arrays.scala"

  test_bootstrapped:
    group: test
    image: lampepfl/dotty:2017-10-07
    commands:
      - cp -R . /tmp/2/ && cd /tmp/2/
      - ./project/scripts/sbt dotty-bootstrapped/testAll
      - ./project/scripts/sbt ";dotty-bench-bootstrapped/jmh:run 1 1 tests/run/arrays.scala"

  test_optimised:
    group: test
    image: lampepfl/dotty:2017-10-07
    commands:
      - cp -R . /tmp/3/ && cd /tmp/3/
      - ./project/scripts/sbt dotty-optimised/testAll

  test_sbt:
    group: test
    image: lampepfl/dotty:2017-10-07
    commands:
      - cp -R . /tmp/4/ && cd /tmp/4/
      - ./project/scripts/sbt sbt-dotty/scripted
    when:
      # sbt scripted tests are slow and don't run on PRs
      event: [ push, tag, deployment ]

  # DOCUMENTATION:
  documentation:
    image: lampepfl/dotty:2017-10-07
    commands:
      - ./project/scripts/genDocs
    secrets: [ bot_pass ]
    when:
      event: push
      # We only generate the documentation for the master branch
      branch: master

  # PUBLISHING:
  # Publishing expect NIGHTLYBUILD or RELEASEBUILD to be set. See dottyVersion in Build.scala
  publish_nightly:
    image: lampepfl/dotty:2017-10-07
    environment:
      - NIGHTLYBUILD=yes
    commands:
      - ./project/scripts/sbtPublish ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    secrets: [ sonatype_user, sonatype_pw, pgp_pw ]
    when:
      event: deployment
      environment: nightly

  publish_release:
    image: lampepfl/dotty:2017-10-07
    environment:
      - RELEASEBUILD=yes
    commands:
      - ./project/scripts/sbtPublish ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    secrets: [ sonatype_user, sonatype_pw, pgp_pw ]
    when:
      event: deployment
      environment: release

  publish_sbt_release:
    image: lampepfl/dotty:2017-10-07
    environment:
      - RELEASEBUILD=yes
    commands:
      - ./project/scripts/sbtPublish ";sbt-dotty/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    secrets: [ sonatype_user, sonatype_pw, pgp_pw ]
    when:
      event: deployment
      environment: sbt_release

  # NOTIFICATIONS:
  slack:
    image: plugins/slack
    channel: dotty
    secrets: [ slack_webhook ]
    when:
      status: [ failure ]
      event: [ push, tag, deployment ]

branches:
  # The gh-pages branch holds the documentation and don't need to be built
  exclude: gh-pages
